name:                EchoBot
version:             0.1.0.0
github:              "hmarat1403/EchoBot"
license:             BSD3
author:              "Marat Khalitov"
maintainer:          "marat540@hotmail.com"
copyright:           "BSD3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Unregistry/EchoBot#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- aeson
- aeson-utils
- bytestring
- text
- http-conduit
- http-types
- mtl
- containers
- directory
library:
  source-dirs: src

executables:
  EchoBot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EchoBot

tests:
  EchoBot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EchoBot
